### ISSUE TITLE
Following message while running Setup.py

### ISSUE THREAD

**Issue by ghost** [muflone/gnome-appfolders-manager#20]
Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    from gnome_appfolders_manager.functions import recursive_glob
  File "/home/saurabh/gnome-appfolders-manager/gnome_appfolders_manager/__init__.py", line 24, in <module>
    import gnome_appfolders_manager.requires
  File "/home/saurabh/gnome-appfolders-manager/gnome_appfolders_manager/requires.py", line 21, in <module>
    import gi
ImportError: No module named gi

**Comment by gusbemacbe** [comment]
HI @saurabhinabys !

You have to run as sudo.

**Comment by muflone** [comment]
the installation script was rewritten using setuptools and also supports installation without permission with
python setup.py install --user
